# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'network_social' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for network_social
	pod 'Firebase/Firestore'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'lottie-ios'
	pod 'Charts'
  target 'network_socialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'network_socialUITests' do
    # Pods for testing
  end

end
